if initialization == 1
    load('data2NcycleEvapo_pond_snow_deten_from1808to2007_S1',...
    'detention_day_point',...
    'evapotransp_day_point',...
    'pond_day_point',...
    'snow_day_point')

    if start_year == 1808
       detention_mm=detention_day_point(:,choose_point);
       evapotransp_mm=evapotransp_day_point(:,choose_point);
       pond_mm=pond_day_point(:,choose_point);
       snow_mm=snow_day_point(:,choose_point); 
    elseif start_year == 1908
        detention_mm=detention_day_point(36501:end,choose_point);
        evapotransp_mm=evapotransp_day_point(36501:end,choose_point);
        pond_mm=pond_day_point(36501:end,choose_point);
        snow_mm=snow_day_point(36501:end,choose_point);
    end
else
    if scenarios == 1
        load('data2NcycleEvapo_pond_snow_deten_from2008to2012_S1',...
            'detention_day_point',...
            'evapotransp_day_point',...
            'pond_day_point',...
            'snow_day_point')
        detention_mm=detention_day_point(:,choose_point);
        evapotransp_mm=evapotransp_day_point(:,choose_point);
        pond_mm=pond_day_point(:,choose_point);
        snow_mm=snow_day_point(:,choose_point);
    elseif scenarios == 2
        load('data2NcycleEvapo_pond_snow_deten_from2008to2012_S2',...
            'detention_day_point',...
            'evapotransp_day_point',...
            'pond_day_point',...
            'snow_day_point')
        detention_mm=detention_day_point(:,choose_point);
        evapotransp_mm=evapotransp_day_point(:,choose_point);
        pond_mm=pond_day_point(:,choose_point);
        snow_mm=snow_day_point(:,choose_point);
    elseif scenarios == 3
        load('data2NcycleEvapo_pond_snow_deten_from2008to2012_S3',...
            'detention_day_point',...
            'evapotransp_day_point',...
            'pond_day_point',...
            'snow_day_point')
        detention_mm=detention_day_point(:,choose_point);
        evapotransp_mm=evapotransp_day_point(:,choose_point);
        pond_mm=pond_day_point(:,choose_point);
        snow_mm=snow_day_point(:,choose_point);
    elseif scenarios == 4
        load('data2NcycleEvapo_pond_snow_deten_from2008to2012_S4',...
            'detention_day_point',...
            'evapotransp_day_point',...
            'pond_day_point',...
            'snow_day_point')
        detention_mm=detention_day_point(:,choose_point);
        evapotransp_mm=evapotransp_day_point(:,choose_point);
        pond_mm=pond_day_point(:,choose_point);
        snow_mm=snow_day_point(:,choose_point);
    elseif scenarios == 5
        load('data2NcycleEvapo_pond_snow_deten_from2008to2107_S5',...
            'detention_day_point',...
            'evapotransp_day_point',...
            'pond_day_point',...
            'snow_day_point')
        detention_mm=detention_day_point(:,choose_point);
        evapotransp_mm=evapotransp_day_point(:,choose_point);
        pond_mm=pond_day_point(:,choose_point);
        snow_mm=snow_day_point(:,choose_point);
    end
end